channels:
  - conda-forge
  - bioconda
dependencies:
  - bowtie >=1.1.1
  - matplotlib
  - numpy
  - pyfasta
  - pysam >0.9.0
  - pyyaml
  - rsem >=1.2.19
  - samtools >= 1.3.1
  - trimmomatic >= 0.33
